# Generated by Django 5.0.6 on 2024-06-13 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0002_coffeeshopcategory_coffeeshopproduct_composition_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeshopproduct',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spa_app.coffeeshopcategory'),
        ),
    ]
