# Generated by Django 5.0.6 on 2024-06-15 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0003_coffeeshopproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeeshopproduct',
            name='price',
            field=models.IntegerField(),
        ),
    ]
