# Generated by Django 5.0.6 on 2024-06-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0005_rename_coffeeshopcategory_coffeecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameModel(
            old_name='TypeCategories',
            new_name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='SpaСategories',
        ),
    ]
