# Generated by Django 5.0.6 on 2024-06-19 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0006_servicetype_rename_typecategories_servicecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='type_of_categories',
            field=models.ManyToManyField(related_name='type_of_categories', to='spa_app.servicecategory'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapists', to='spa_app.salon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_therapists', to='spa_app.servicetype')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.employee'),
        ),
        migrations.DeleteModel(
            name='MassageTherapist',
        ),
    ]
