# Generated by Django 5.0.6 on 2024-06-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0007_servicetype_type_of_categories_employee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapistavailability',
            name='day',
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='composition',
        ),
        migrations.RemoveField(
            model_name='therapistavailability',
            name='therapist',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration', models.DurationField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='type_categories_image/')),
                ('composition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composition', to='spa_app.composition')),
            ],
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='type_of_categories',
            field=models.ManyToManyField(related_name='type_of_categories', to='spa_app.procedure'),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
        migrations.DeleteModel(
            name='ServiceCategory',
        ),
        migrations.DeleteModel(
            name='TherapistAvailability',
        ),
    ]
