# Generated by Django 5.0.6 on 2024-06-20 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0008_remove_therapistavailability_day_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicetype',
            old_name='type_of_categories',
            new_name='procedures',
        ),
        migrations.AddField(
            model_name='employee',
            name='rating',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
