# Generated by Django 5.0.6 on 2024-06-22 14:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0013_employee_review_count_alter_employee_rating_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=3600), 'Regular'), (datetime.timedelta(seconds=5400), 'Long')]),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.procedure')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spa_app.schedule')),
            ],
        ),
    ]
