# Generated by Django 5.0.6 on 2024-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0016_alter_procedure_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
