# Generated by Django 5.0.6 on 2024-07-06 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0018_gallerycategory_alter_record_schedule_galleryimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcedureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('description', models.TextField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='procedure',
            name='composition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='spa_app.composition'),
        ),
        migrations.AddField(
            model_name='procedure',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='spa_app.procedurecategory'),
        ),
    ]
