# Generated by Django 5.0.6 on 2024-07-06 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0019_procedurecategory_alter_procedure_composition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedurecategory',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
