# Generated by Django 5.0.6 on 2024-07-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0022_alter_procedure_image_alter_procedurecategory_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='type_categories_image/'),
        ),
    ]
