# Generated by Django 5.0.6 on 2024-07-07 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0023_alter_procedure_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
