# Generated by Django 5.0.6 on 2024-07-07 15:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0025_employee_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='composition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='spa_app.composition'),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='duration',
            field=models.DurationField(choices=[(datetime.timedelta(seconds=3600), 'Regular'), (datetime.timedelta(seconds=5400), 'Long'), (datetime.timedelta(seconds=7200), 'Very Long')]),
        ),
    ]
