# Generated by Django 5.0.6 on 2024-07-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0026_alter_procedure_composition_alter_procedure_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerole',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='servicerole',
            name='procedures',
            field=models.ManyToManyField(blank=True, null=True, related_name='procedures', to='spa_app.procedure'),
        ),
    ]
