# Generated by Django 5.0.6 on 2024-07-08 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0027_servicerole_is_admin_alter_servicerole_procedures'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='composition',
            name='description',
        ),
        migrations.AddField(
            model_name='composition',
            name='contraindications',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='firm',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='composition',
            name='product_component',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
