# Generated by Django 5.0.6 on 2024-07-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0028_remove_composition_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
