# Generated by Django 5.0.6 on 2024-07-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0030_alter_spauser_first_name_alter_spauser_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spauser',
            name='profile_image',
            field=models.ImageField(default='../media/default_profile_image/default-avatar.jng', upload_to=''),
        ),
    ]
