# Generated by Django 5.0.6 on 2024-07-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0034_alter_spauser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerole',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, related_name='employees', to='spa_app.employee'),
        ),
    ]
