# Generated by Django 5.0.6 on 2024-07-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0035_servicerole_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerole',
            name='employees',
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(related_name='employees', to='spa_app.servicerole'),
        ),
        migrations.AlterField(
            model_name='servicerole',
            name='procedures',
            field=models.ManyToManyField(blank=True, null=True, related_name='roles', to='spa_app.procedure'),
        ),
    ]
