# Generated by Django 5.0.6 on 2024-07-10 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0036_remove_servicerole_employees_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedurecategory',
            name='roles',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='spa_app.servicerole'),
        ),
    ]
