# Generated by Django 5.0.6 on 2024-07-11 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0037_procedurecategory_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerole',
            name='employees',
            field=models.ManyToManyField(related_name='employee_roles', to='spa_app.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='role',
            field=models.ManyToManyField(related_name='roles', to='spa_app.servicerole'),
        ),
        migrations.AlterField(
            model_name='procedurecategory',
            name='roles',
            field=models.ManyToManyField(related_name='categories', to='spa_app.servicerole'),
        ),
        migrations.AlterField(
            model_name='servicerole',
            name='procedures',
            field=models.ManyToManyField(related_name='roles', to='spa_app.procedure'),
        ),
    ]
