# Generated by Django 5.0.6 on 2024-07-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0038_servicerole_employees_alter_employee_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
