# Generated by Django 5.0.6 on 2024-07-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spa_app', '0039_alter_record_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffeeproduct',
            name='compound',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
