export const paths = {
  coffeeProducts: "coffee-products/",
  coffeeCategories: "coffee-categories/",
  employee: "employee/",
  role: "role/",
  procedure: "procedure/",
  composition: "composition/",
  salon: "salon/",
  review: "review/",
  schedule: "schedule/",
  record: "record/",
  galleryCategory: "gallery-category/",
  galleryImage: "gallery-image/",
  procedureCategory: "procedure-category/",
  register: "register/",
  auth: "auth/",
};
